from .ui_integration.ens_registration_ui_workflow import ENSRegistrationUIWorkflow
from .contract_abi_integratrion.ens_set_text import ENSSetTextWorkflow
from .contract_abi_integratrion.ens_set_primary_name import ENSSetPrimaryNameWorkflow
from .contract_abi_integratrion.ens_set_avatar_nft import ENSSetAvatarNFTWorkflow
from .contract_abi_integratrion.ens_registration_contract_workflow import ENSRegistrationContractWorkflow