import re
from logging import basicConfig, INFO
import time
import json
import uuid
import os
import requests
import sha3 # 'pip install pysha3'
from idna import encode, IDNAError

from typing import Any, Dict, List, Optional, Union, Literal, TypedDict, Callable
from dataclasses import dataclass, asdict

from playwright.sync_api import TimeoutError as PlaywrightTimeoutError

import env
from utils import TENDERLY_FORK_URL, w3
from ..base import BaseUIWorkflow, MultiStepResult, BaseMultiStepWorkflow, WorkflowStepClientPayload, StepProcessingResult, RunnableStep, tenderly_simulate_tx, setup_mock_db_objects, Result
from database.models import (
    db_session, MultiStepWorkflow, WorkflowStep, WorkflowStepStatus, WorkflowStepUserActionType, ChatMessage, ChatSession, SystemConfig
)


def keccak_256(data):
    k = sha3.keccak_256()
    k.update(data)
    return k.hexdigest()

def to_unicode(name):
    try:
        return encode(name, uts46=True, transitional=False, std3_rules=True).decode('utf-8')
    except IDNAError as e:
        return name

def namehash(input_name):
    node = bytes.fromhex("00" * 32)

    name = to_unicode(input_name)

    if name:
        labels = name.split(".")

        for label in reversed(labels):
            label_sha = bytes.fromhex(keccak_256(label.encode()))
            node_sha = keccak_256(node + label_sha)
            node = bytes.fromhex(node_sha)

    return "0x" + node.hex()


class ENSSetText():
    def __init__(self, wallet_chain_id: int, wallet_address: str, chat_message_id: str, params: Dict) -> None:
        self.wallet_chain_id = wallet_chain_id
        self.wallet_address = wallet_address
        self.chat_message_id = chat_message_id
        self.params = params
        self.parsed_user_request = f"{params['name']}: set {params['key']} to {params['value']}"
        with open('./ui_workflows/ens/ENS_resolver.abi', 'r') as f:
            self.contract_abi_dict = json.load(f)


    def run(self) -> Result:
        node = namehash(self.params['name'])
        contract_address = "0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41"
        # Create a contract object
        contract = w3.eth.contract(address=w3.toChecksumAddress(contract_address), abi=self.contract_abi_dict)
        # Construct the transaction input data
        tx_input = contract.encodeABI(fn_name='setText', args=[node, self.params['key'], self.params['value']])

        tx = {
         'gas': '0x14e1c',  #we need a way to set gas correctly?
         'from': self.wallet_address, 
         'to': contract_address, 
         'data': tx_input
         }


        # return the transaction input
        description = f"Transaction on ENS to set field {params['key']} to  {params['value']} for ENS name {params['name']}"
        return Result(
                status="success", 
                tx=tx,
                is_approval_tx=False, 
                parsed_user_request=self.parsed_user_request,
                description=description
            )


# Invoke this with python3 -m ui_workflows.ens.ens_setText
if __name__ == "__main__":
    tenderly_api_access_key = os.environ.get("TENDERLY_API_ACCESS_KEY", None)
    ens_to_set = "vitalik.eth"
    wallet_address = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
    wallet_chain_id = 1  # Tenderly Mainnet Fork
    mock_chat_session = ChatSession()
    params: Dict = {"name": "vitalik.eth", "key":"url", "value":"https://twitter.com/VitalikButerin"}
    result: Result = ENSSetText(wallet_chain_id, wallet_address, mock_chat_session.id, params).run()

    tenderly_simulate_tx(tenderly_api_access_key, wallet_address, result.tx)
    # tx input should equal 
    # '0x10f13a8cee6c4522aab0003e8d14cd40a6af439055fd2577951148c14b6cea9a53475835000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000375726c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002268747470733a2f2f747769747465722e636f6d2f566974616c696b4275746572696e000000000000000000000000000000000000000000000000000000000000'
    # as generated by ENS frontend
    print(result)