steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: [
    'build', '-t',
    'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}',
    '--build-arg=ENV_FILENAME=${_ENV_FILENAME}',
    '.',
   ]
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - '${_SERVICE_NAME}'
   - '--image'
   - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
   - '--region'
   - 'us-east1'

# _SERVICE_NAME and _ENV_FILENAME are custom substitutions defined within
# the GCP Cloud Build triggers

images:
 - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
