"""Add shared session and shared message tables

Revision ID: 1f62c956d8a9
Revises: f97c351eea52
Create Date: 2023-07-19 00:45:57.426545

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f62c956d8a9'
down_revision = 'f97c351eea52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_session',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_chat_session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['source_chat_session_id'], ['chat_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('shared_session_user', 'shared_session', ['user_id'], unique=False)
    op.create_table('shared_message',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('shared_session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('system_config_id', sa.Integer(), nullable=False),
    sa.Column('source_chat_message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['shared_session_id'], ['shared_session.id'], ),
    sa.ForeignKeyConstraint(['source_chat_message_id'], ['chat_message.id'], ),
    sa.ForeignKeyConstraint(['system_config_id'], ['system_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('shared_message_by_sequence_number', 'shared_message', ['shared_session_id', 'sequence_number', 'created'], unique=False)
    op.add_column('chat_message', sa.Column('source_shared_message_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('chat_session', sa.Column('source_shared_session_id', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'source_shared_session_id')
    op.drop_column('chat_message', 'source_shared_message_id')
    op.drop_index('shared_message_by_sequence_number', table_name='shared_message')
    op.drop_table('shared_message')
    op.drop_index('shared_session_user', table_name='shared_session')
    op.drop_table('shared_session')
    # ### end Alembic commands ###
