"""Add creation timestamp to user-lookup indices on chat session and shared session

Revision ID: 7cc8cbfe072d
Revises: a9e5b4f0e5c5
Create Date: 2023-08-01 00:02:42.997895

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7cc8cbfe072d'
down_revision = 'a9e5b4f0e5c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chat_session_user', table_name='chat_session')
    op.create_index('chat_session_by_user_deleted_created', 'chat_session', ['user_id', 'deleted', 'created'], unique=False)
    op.drop_index('shared_session_user', table_name='shared_session')
    op.create_index('shared_session_by_user_deleted_created', 'shared_session', ['user_id', 'deleted', 'created'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('shared_session_by_user_deleted_created', table_name='shared_session')
    op.create_index('shared_session_user', 'shared_session', ['user_id', 'deleted'], unique=False)
    op.drop_index('chat_session_by_user_deleted_created', table_name='chat_session')
    op.create_index('chat_session_user', 'chat_session', ['user_id', 'deleted'], unique=False)
    # ### end Alembic commands ###
