"""Drop privacy type

Revision ID: 878efb341d24
Revises: aac1388f4b43
Create Date: 2023-06-28 14:50:27.618236

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '878efb341d24'
down_revision = 'aac1388f4b43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'privacy_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('privacy_type', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
