"""Add deleted datetime column to chat session and shared session

Revision ID: a9e5b4f0e5c5
Revises: 1f62c956d8a9
Create Date: 2023-07-21 17:49:31.247744

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a9e5b4f0e5c5'
down_revision = '1f62c956d8a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('deleted', sa.DateTime(), nullable=True))
    op.drop_index('chat_session_user', table_name='chat_session')
    op.create_index('chat_session_user', 'chat_session', ['user_id', 'deleted'], unique=False)
    op.add_column('shared_session', sa.Column('deleted', sa.DateTime(), nullable=True))
    op.drop_index('shared_session_user', table_name='shared_session')
    op.create_index('shared_session_user', 'shared_session', ['user_id', 'deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('shared_session_user', table_name='shared_session')
    op.create_index('shared_session_user', 'shared_session', ['user_id'], unique=False)
    op.drop_column('shared_session', 'deleted')
    op.drop_index('chat_session_user', table_name='chat_session')
    op.create_index('chat_session_user', 'chat_session', ['user_id'], unique=False)
    op.drop_column('chat_session', 'deleted')
    # ### end Alembic commands ###
