"""Initial schema snapshot (at alembic adoption time)

Revision ID: b37b4d7dd234
Revises: 
Create Date: 2023-06-09 16:38:37.313810

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
import database.models

# revision identifiers, used by Alembic.
revision = 'b37b4d7dd234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multistep_workflow',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chat_message_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('wallet_chain_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_json'), 'system_config', ['json'], unique=False)
    op.create_table('chat_message',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('system_config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], ),
    sa.ForeignKeyConstraint(['system_config_id'], ['system_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('chat_message_by_sequence_number', 'chat_message', ['chat_session_id', 'sequence_number', 'created'], unique=False)
    op.create_table('workflow_step',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('workflow_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('user_action_type', sqlalchemy_utils.ChoiceType(database.models.WorkflowStepUserActionType, impl=sa.Integer()), nullable=False),
    sa.Column('user_action_data', sa.String(), nullable=True),
    sa.Column('status', sqlalchemy_utils.ChoiceType(database.models.WorkflowStepStatus, impl=sa.Integer()), nullable=False),
    sa.Column('status_message', sa.String(), nullable=True),
    sa.Column('step_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['multistep_workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_feedback',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('chat_message_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('feedback_status', sqlalchemy_utils.ChoiceType(database.models.FeedbackStatus, impl=sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('chat_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message_feedback')
    op.drop_table('workflow_step')
    op.drop_index('chat_message_by_sequence_number', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_system_config_json'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_table('multistep_workflow')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
