"""Add privacy type with default

Revision ID: c0f09e7da34d
Revises: 878efb341d24
Create Date: 2023-06-28 14:52:22.558737

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import database.models

# revision identifiers, used by Alembic.
revision = 'c0f09e7da34d'
down_revision = '878efb341d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('privacy_type', sqlalchemy_utils.ChoiceType(database.models.PrivacyType, impl=sa.Integer()), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'privacy_type')
    # ### end Alembic commands ###
