"""user auth

Revision ID: e52faee0a294
Revises: b37b4d7dd234
Create Date: 2023-06-09 16:59:19.895890

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
import database.models

# revision identifiers, used by Alembic.
revision = 'e52faee0a294'
down_revision = 'b37b4d7dd234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('wallet_address_unique', 'wallet', ['wallet_address'], unique=True)
    op.create_table('user_wallet',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('wallet_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'wallet_id')
    )
    op.create_index('wallet_user_id', 'user_wallet', ['wallet_id', 'user_id'], unique=False)
    op.add_column('chat_session', sa.Column('privacy_type', sqlalchemy_utils.ChoiceType(database.models.PrivacyType, impl=sa.Integer()), nullable=False))
    op.add_column('chat_session', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index('chat_session_user', 'chat_session', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_session', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_session', type_='foreignkey')
    op.drop_index('chat_session_user', table_name='chat_session')
    op.drop_column('chat_session', 'user_id')
    op.drop_column('chat_session', 'privacy_type')
    op.drop_index('wallet_user_id', table_name='user_wallet')
    op.drop_table('user_wallet')
    op.drop_index('wallet_address_unique', table_name='wallet')
    op.drop_table('wallet')
    op.drop_table('user')
    # ### end Alembic commands ###
