---
version: '3.4'
services:
  chat-db:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=lVIu2U0lBctiYBScboAJ
      - POSTGRES_USER=chatdb
      - POSTGRES_DB=chatdb
    ports:
      - 5433:5432
    volumes:
    - cacti_pg_data:/var/lib/postgresql/data
  weaviate:
    volumes:
    - cacti_weaviate_data:/var/lib/weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.20.3
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'example-secret-key-123'
      AUTHENTICATION_APIKEY_USERS: 'cacti-app'
      
volumes:
  cacti_pg_data:
  cacti_weaviate_data:
