import os

OPENAI_API_KEY = "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"
CENTER_API_KEY = os.getenv('CENTER_API_KEY', 'key8f1af05afe473107c3ea2556')
ETHERSCAN_API_KEY = 'ZCUTVCPHAJ5YRNB6SZTJN9ZV24FBEX86GJ'
OPENSEA_API_KEY = os.getenv('OPENSEA_API_KEY', '')
TENDERLY_API_KEY = os.getenv('TENDERLY_API_KEY', None)

TENDERLY_FORK_BASE_URL = "https://rpc.tenderly.co/fork"
DEFAULT_MAINNET_FORK_ID = "902db63e-9c5e-415b-b883-5701c77b3aa7"
TENDERLY_FORK_URL = f"{TENDERLY_FORK_BASE_URL}/{DEFAULT_MAINNET_FORK_ID}"