# Dev environment

# GCP SQL instance: chatdb-dev
chatdb:
  host: 34.139.225.26
  port: 5432
  user: chatdb
  password: lVIu2U0lBctiYBScboAJ

# GCP SQL instance: scrapedb
scrapedb:
  host: 34.23.168.19
  port: 5432
  user: chatdb
  password: lVIu2U0lBctiYBScboAJ

# TODO: set up https
# GCP VM: weaviate-dev
weaviate:
  protocol: http
  host: 35.211.169.16
  port: 8080
  user: chatweb3
  password: q0jficzXOA69T5FWgAeT

# FastAPI server
server:
  host: dev--ironclad-parent.netlify.app
  origins:
  - https://dev--ironclad-parent.netlify.app
  secret_key: wMLunxkwpWJf5iyDTHGm3iGqLtHOf0vQ+gOzv3HipIM=
