# Dev environment

# GCP SQL instance: chat-db-dev
postgres:
  host: 34.23.31.248
  port: 5432
  user: chatdb
  password: lVIu2U0lBctiYBScboAJ

# TODO: set up https
# GCP VM: weaviate-dev
weaviate:
  protocol: http
  host: 35.243.192.205
  port: 8080
  user: chatweb3
  password: q0jficzXOA69T5FWgAeT
