# Prod environment

# GCP SQL instance: chatdb-prod
chatdb:
  host: 34.73.235.128
  port: 5432
  user: chatdb
  password: lVIu2U0lBctiYBScboAJ

# GCP SQL instance: scrapedb
scrapedb:
  host: 34.23.168.19
  port: 5432
  user: chatdb
  password: lVIu2U0lBctiYBScboAJ

# TODO: set up https
# GCP VM: weaviate-prod
weaviate:
  protocol: http
  host: 35.211.102.62
  port: 8080
  user: chatweb3
  password: q0jficzXOA69T5FWgAeT

# FastAPI server
server:
  origins:
  - https://ironclad-parent.netlify.app/
