# Prod environment

# GCP SQL instance: chat-db-prod
postgres:
  host: 34.23.222.69
  port: 5432
  user: chatdb
  password: lVIu2U0lBctiYBScboAJ

# TODO: set up https
# GCP VM: weaviate-prod
weaviate:
  protocol: http
  host: 35.231.214.53
  port: 8080
  user: chatweb3
  password: q0jficzXOA69T5FWgAeT
