# This workflow will check if all widgets in the file and index have corresponding textual translation
# More info in README 'Steps to add new widget command'

name: Check widget translation

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  main:
    name: Check widget translation
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          path: backend

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt

      - name: Set environment for branch
        run: |
          if [[ ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}} == 'master' ]]; then
            echo "ENV_TAG=prod" >> "$GITHUB_ENV"
          else
            echo "ENV_TAG=dev" >> "$GITHUB_ENV"
            echo "SERVER_HOST=" >> "$GITHUB_ENV"
            echo "SERVER_ORIGINS=" >> "$GITHUB_ENV"
            echo "SERVER_SECRET_KEY=" >> "$GITHUB_ENV"
          fi

      - name: Check widget translation
        run: |
          cd backend
          python -m scripts.check_widget_translation
